### ISSUE TITLE
CM4 Direction for `throttle_time_ms` Mismatch

### ISSUE THREAD

**Issue by Spiderpig86** [codecrafters-io/kafka-tester#34]
The directions mention that any `throttle_time_ms` is accepted 

https://github.com/codecrafters-io/kafka-tester/blob/234e0995ded10bbc45cc1ed851152b3a50907767/internal/test_helpers/course_definition.yml#L525)

But the test case strictly asserts it is 0 
https://github.com/codecrafters-io/kafka-tester/blob/234e0995ded10bbc45cc1ed851152b3a50907767/internal/stagef4.go#L90

This is reproducible by modifying the response `throttle_time_ms` to a non-zero value.

**Comment by ryan-gang** [comment]
Thanks, @Spiderpig86, for highlighting the issue! We've fixed it in https://github.com/codecrafters-io/build-your-own-kafka/pull/16.
